-- =====================================================
-- SCRIPT SQL PARA CRIAÇÃO DAS TABELAS NO ORACLE
-- Mottu API - Sistema de Gerenciamento de Motos e Filiais
-- =====================================================

-- Criar tabela de Filiais
CREATE TABLE Filiais (
    Id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Nome NVARCHAR2(100) NOT NULL,
    Endereco_Logradouro NVARCHAR2(100) NOT NULL,
    Endereco_Numero NVARCHAR2(10) NOT NULL,
    Endereco_Complemento NVARCHAR2(50),
    Endereco_Bairro NVARCHAR2(50) NOT NULL,
    Endereco_Cidade NVARCHAR2(50) NOT NULL,
    Endereco_Estado NVARCHAR2(2) NOT NULL,
    Endereco_CEP NVARCHAR2(8) NOT NULL,
    Telefone NVARCHAR2(15) NOT NULL,
    Ativo NUMBER(1) DEFAULT 1 NOT NULL,
    DataCriacao TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DataAtualizacao TIMESTAMP(7)
);

-- Criar tabela de Motos
CREATE TABLE Motos (
    Id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    Placa NVARCHAR2(7) NOT NULL,
    Modelo NVARCHAR2(50) NOT NULL,
    Ano NUMBER(10) NOT NULL,
    Cor NVARCHAR2(30) NOT NULL,
    Disponivel NUMBER(1) DEFAULT 1 NOT NULL,
    DataCriacao TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DataAtualizacao TIMESTAMP(7),
    FilialId NUMBER(10) NOT NULL,
    CONSTRAINT FK_Motos_Filiais_FilialId 
        FOREIGN KEY (FilialId) 
        REFERENCES Filiais(Id) 
        ON DELETE RESTRICT
);

-- Criar índice para melhor performance
CREATE INDEX IX_Motos_FilialId ON Motos(FilialId);

-- Criar índice único para placa (evitar duplicatas)
CREATE UNIQUE INDEX IX_Motos_Placa ON Motos(Placa);

-- Inserir dados de exemplo
INSERT INTO Filiais (Nome, Endereco_Logradouro, Endereco_Numero, Endereco_Complemento, Endereco_Bairro, Endereco_Cidade, Endereco_Estado, Endereco_CEP, Telefone, Ativo) 
VALUES ('Filial São Paulo', 'Rua das Flores', '123', 'Sala 1', 'Centro', 'São Paulo', 'SP', '01234567', '(11) 99999-9999', 1);

INSERT INTO Filiais (Nome, Endereco_Logradouro, Endereco_Numero, Endereco_Complemento, Endereco_Bairro, Endereco_Cidade, Endereco_Estado, Endereco_CEP, Telefone, Ativo) 
VALUES ('Filial Rio de Janeiro', 'Avenida Copacabana', '456', 'Loja 2', 'Copacabana', 'Rio de Janeiro', 'RJ', '22000000', '(21) 88888-8888', 1);

INSERT INTO Motos (Placa, Modelo, Ano, Cor, Disponivel, FilialId) 
VALUES ('ABC1234', 'Honda CG 160', 2023, 'Vermelha', 1, 1);

INSERT INTO Motos (Placa, Modelo, Ano, Cor, Disponivel, FilialId) 
VALUES ('DEF5678', 'Yamaha Fazer 250', 2022, 'Azul', 1, 1);

INSERT INTO Motos (Placa, Modelo, Ano, Cor, Disponivel, FilialId) 
VALUES ('GHI9012', 'Honda Biz 125', 2024, 'Branca', 1, 2);

-- Verificar se as tabelas foram criadas
SELECT 'Filiais' as Tabela, COUNT(*) as Registros FROM Filiais
UNION ALL
SELECT 'Motos' as Tabela, COUNT(*) as Registros FROM Motos;

-- Comentários das tabelas
COMMENT ON TABLE Filiais IS 'Tabela de filiais da Mottu';
COMMENT ON TABLE Motos IS 'Tabela de motos da Mottu';

-- Comentários das colunas principais
COMMENT ON COLUMN Filiais.Nome IS 'Nome da filial';
COMMENT ON COLUMN Filiais.Ativo IS 'Status da filial (1=Ativa, 0=Inativa)';
COMMENT ON COLUMN Motos.Placa IS 'Placa da moto (única)';
COMMENT ON COLUMN Motos.Disponivel IS 'Status de disponibilidade (1=Disponível, 0=Indisponível)';
COMMENT ON COLUMN Motos.FilialId IS 'ID da filial proprietária da moto';

-- Commit das alterações
COMMIT;

-- Exibir mensagem de sucesso
SELECT 'Script executado com sucesso! Tabelas criadas e dados de exemplo inseridos.' as Status FROM DUAL;
